services:
  - type: web
    name: api-gateway
    env: node
    buildCommand: npm ci && npx nx build api-gateway --prod
    startCommand: node dist/apps/api-gateway/main.js
    autoDeploy: false
    branch: main

  - type: static
    name: nav-shell
    buildCommand: npm ci && npx nx build nav-shell --prod
    staticPublishPath: dist/apps/nav-shell/browser
    autoDeploy: false
    branch: main
