/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppButton {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default 'Click me'
         */
        "label": string;
        /**
          * @default 'primary'
         */
        "variant": 'primary' | 'secondary';
    }
    interface AppCard {
        /**
          * The card title
         */
        "cardTitle": string;
        /**
          * The card description text
         */
        "description": string;
        /**
          * Alt text for the image (defaults to "Card image")
          * @default 'Card image'
         */
        "imageAlt": string;
        /**
          * Optional image URL to display at the top of the card
         */
        "imageUrl"?: string;
        /**
          * Card variant: default, highlighted, or compact
          * @default 'default'
         */
        "variant": | 'default'
		| 'highlighted'
		| 'compact';
    }
    /**
     * Icon component that loads SVG icons from CDN with caching, sanitization, and theming.
     */
    interface AppIcon {
        /**
          * Whether icon is decorative only
         */
        "ariaHidden"?: boolean;
        /**
          * Custom aria-label (defaults to icon name)
         */
        "ariaLabel"?: string;
        /**
          * Icon color - either a jewel-tone palette key or any CSS color value
         */
        "color"?: string;
        /**
          * Icon name (e.g., "angular", "react", "typescript")
         */
        "name": string;
        /**
          * Icon size variant
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
    }
}
export interface AppCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAppCardElement;
}
declare global {
    interface HTMLAppButtonElement extends Components.AppButton, HTMLStencilElement {
    }
    var HTMLAppButtonElement: {
        prototype: HTMLAppButtonElement;
        new (): HTMLAppButtonElement;
    };
    interface HTMLAppCardElementEventMap {
        "cardClick": {
		title: string
	};
    }
    interface HTMLAppCardElement extends Components.AppCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAppCardElementEventMap>(type: K, listener: (this: HTMLAppCardElement, ev: AppCardCustomEvent<HTMLAppCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAppCardElementEventMap>(type: K, listener: (this: HTMLAppCardElement, ev: AppCardCustomEvent<HTMLAppCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAppCardElement: {
        prototype: HTMLAppCardElement;
        new (): HTMLAppCardElement;
    };
    /**
     * Icon component that loads SVG icons from CDN with caching, sanitization, and theming.
     */
    interface HTMLAppIconElement extends Components.AppIcon, HTMLStencilElement {
    }
    var HTMLAppIconElement: {
        prototype: HTMLAppIconElement;
        new (): HTMLAppIconElement;
    };
    interface HTMLElementTagNameMap {
        "app-button": HTMLAppButtonElement;
        "app-card": HTMLAppCardElement;
        "app-icon": HTMLAppIconElement;
    }
}
declare namespace LocalJSX {
    interface AppButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default 'Click me'
         */
        "label"?: string;
        /**
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary';
    }
    interface AppCard {
        /**
          * The card title
         */
        "cardTitle": string;
        /**
          * The card description text
         */
        "description": string;
        /**
          * Alt text for the image (defaults to "Card image")
          * @default 'Card image'
         */
        "imageAlt"?: string;
        /**
          * Optional image URL to display at the top of the card
         */
        "imageUrl"?: string;
        /**
          * Emitted when the card is clicked
         */
        "onCardClick"?: (event: AppCardCustomEvent<{
		title: string
	}>) => void;
        /**
          * Card variant: default, highlighted, or compact
          * @default 'default'
         */
        "variant"?: | 'default'
		| 'highlighted'
		| 'compact';
    }
    /**
     * Icon component that loads SVG icons from CDN with caching, sanitization, and theming.
     */
    interface AppIcon {
        /**
          * Whether icon is decorative only
         */
        "ariaHidden"?: boolean;
        /**
          * Custom aria-label (defaults to icon name)
         */
        "ariaLabel"?: string;
        /**
          * Icon color - either a jewel-tone palette key or any CSS color value
         */
        "color"?: string;
        /**
          * Icon name (e.g., "angular", "react", "typescript")
         */
        "name": string;
        /**
          * Icon size variant
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
    }
    interface IntrinsicElements {
        "app-button": AppButton;
        "app-card": AppCard;
        "app-icon": AppIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-button": LocalJSX.AppButton & JSXBase.HTMLAttributes<HTMLAppButtonElement>;
            "app-card": LocalJSX.AppCard & JSXBase.HTMLAttributes<HTMLAppCardElement>;
            /**
             * Icon component that loads SVG icons from CDN with caching, sanitization, and theming.
             */
            "app-icon": LocalJSX.AppIcon & JSXBase.HTMLAttributes<HTMLAppIconElement>;
        }
    }
}
